### ISSUE TITLE
Hyperspace: Invalid hash in eth Transaction Receipt topic makes ethers.js tx.wait() hang

### ISSUE THREAD

**Issue by scotthconner** [filecoin-project/ref-fvm#1534] opened 2023-01-22 20:14 UTC
Since about Thursday-ish, I've noticed that any clients relying on ethers.js to poll for a transaction receipt to ensure transaction block confirmations hangs.

This occurs in the browser (wagmi useWaitForTransaction never returning), as well as on the command line (using either tx.wait() in ethers.js or deployProxy() and similar workflows from OZ that use confirmation count as a way to ensure the transaction was properly included, and not just put into the mem-pool, but ultimately replaced, etc.

In digging into ethers.js, I found that the transaction receipt is in fact returning, but one of the topics has a malformed hash (looks too long), and ethers.js is silently failing and just continuing to poll. Here is the output from my tracing inside of ethers.js

```
{
  address: '0x5f1eb3a09675974795636b1812793b2c87ca9606',
  data: '0x',
  topics: [
    '0x5820bc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b',
    '0x0000000000000000000000546d3d908bc8e8161d31c485892be1df9cc560dcaa'
  ],
  removed: false,
  logIndex: '0x0',
  transactionIndex: '0x0',
  transactionHash: '0xa4f473c11fa97db24797c081556afa8562123ea8373ac2beeda0d9e7e68171ac',
  blockHash: '0x64ef5f0e78a5c5f83bcad7d89a71b4572640e3f7fa9aa92517f55eb35768bbd3',
  blockNumber: '0x4a21'
}
ERROR!
**Error: invalid hash (argument="value", value="0x5820bc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b", code=INVALID_ARGUMENT, version=providers/5.7.0)**
    at Logger.makeError (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.throwArgumentError (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
    at Formatter.hash (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/providers/src.ts/formatter.ts:270:27)
    at /Users/scotthconner/projects/smartrust/node_modules/@ethersproject/providers/src.ts/formatter.ts:499:2
    at Array.forEach (<anonymous>)
    at Object.topics (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/providers/src.ts/formatter.ts:498:18)
    at Function.Formatter.check (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/providers/src.ts/formatter.ts:455:29)
    at Formatter.receiptLog (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/providers/src.ts/formatter.ts:393:26)
    at /Users/scotthconner/projects/smartrust/node_modules/@ethersproject/providers/src.ts/formatter.ts:499:2 {
  reason: 'invalid hash',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: '0x5820bc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b',
  checkKey: 'topics',
  checkValue: [
    '0x5820bc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b',
    '0x0000000000000000000000546d3d908bc8e8161d31c485892be1df9cc560dcaa'
  ]
}
```

In this case, the transaction returned a topic of **0x5820bc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b** which fails to meet format requirements, and is considered an invalid hash. Because of this, ethers.js never registers the receipt as confirmed and the clients hang.

**Comment by scotthconner** [comment] 2023-01-22 20:28
Might this be related to: https://github.com/filecoin-project/ref-fvm/issues/1420 ?

**Comment by scotthconner** [comment] 2023-01-22 20:30
I'm wondering if its related to the CBOR changes made on the 19th.

**Comment by scotthconner** [comment] 2023-01-22 20:57
Might also be related to https://github.com/filecoin-project/ref-fvm/issues/1345

**Comment by raulk** [comment] 2023-01-22 21:54
Nice find! Looks like we're not stripping the CBOR framing from the topic:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/1101242/213942340-a5b9df05-94a5-47e3-b454-c61949f2428e.png">

(From https://cbor.nemo157.com/)

**Comment by raulk** [comment] 2023-01-22 21:54
This is also the reason why Remix IDE is not able to parse logs according to the contract's ABI (and therefore fails to show logs even though they've been emitted).

**Comment by iand** [comment] 2023-01-23 15:07
Should be fixed by https://github.com/filecoin-project/lotus/pull/10083

**Comment by tzapu** [comment] 2023-01-25 14:15
i can confirm i had this issue with both `tx.wait()`  and `provider.waitForTransaction(tx.hash)` in various lotus builds ( branches: release/v1.20.0 , ntwk/hyperspace, releases: v1.20.0-hyperpsace-0119, commits: 8f0193583adeb2f6d733bd640edc080135721d07, 2a3989e4bd446b7f6ccee52ad6387b937072cf7f )
the fix above seems to sort it for me. gg

**Comment by tzapu** [comment] 2023-01-27 09:20
i can confirm `release/v1.20.0` works properly now. thank you

**Closed** 2023-02-05 19:30 UTC
Labels: Topic: Ethereum JSON-RPC
