### ISSUE TITLE
Predictable actor address generation (CREATE2)

### ISSUE THREAD

**Issue by anorth** [filecoin-project/ref-fvm#733] opened 2022-06-09 04:08 UTC
This is a tracking issue for a proposal that has been made over in FIPs: https://github.com/filecoin-project/FIPs/discussions/379

**Comment by maciejwitowski** [comment] 2022-10-07 13:05
Closing as duplicate of https://github.com/filecoin-project/ref-fvm/issues/680 which has been referenced in more places.

**Closed by maciejwitowski** 2022-10-07 13:05 UTC
Labels: MIGRATED
