### ISSUE TITLE
Fix Lotus to feed the correct tipset timestamp when backfilling null rounds

### ISSUE THREAD

**Issue by raulk** [filecoin-project/ref-fvm#1643] opened 2023-02-06 12:10 UTC
See https://github.com/filecoin-project/FIPs/discussions/592#discussioncomment-4881731.

**Comment by arajasek** [comment] 2023-02-06 16:37
Duplicate of #1632?

**Comment by raulk** [comment] 2023-02-06 16:59
Indeed!

**Closed** 2023-02-06 16:59 UTC
