### ISSUE TITLE
Transaction cancellation bug - reported as a part of FVM bulletproofing

### ISSUE THREAD

**Issue by BlocksOnAChain** [filecoin-project/ref-fvm#1708] opened 2023-03-13 10:28 UTC
We found a potential bug regarding transaction cancellation. 
When we try to deploy a contract and cancel the transaction from Metamask on EVM (Sepolia testnet), the transaction is canceled successfully, and the contract is not deployed. 
On the other hand, when we try to cancel the same transaction on FEVM (Hyperspace testnet and localnet), the transaction is not canceled, and the contract is deployed.

**Comment by BlocksOnAChain** [comment] 2023-03-13 10:28
CC: @maciejwitowski for prioritization and review

**Comment by Stebalien** [comment] 2023-03-13 19:11
Fixed as part of https://github.com/filecoin-project/lotus/issues/10415. Duplicate of https://github.com/filecoin-project/lotus/issues/10376.

Unfortunately, this bug will continue to show up until the network upgrades and includes those patches. They have been pulled into 1.20.3, but that release isn't mandatory.

**Closed by Stebalien** 2023-03-13 19:11 UTC
Labels: Kind: Bug
