### ISSUE TITLE
[BUG] Incorrect chain_id

### ISSUE THREAD

**Issue by amany9000** [filecoin-project/ref-fvm#1218] opened 2022-12-07 20:39 UTC
In truffle, [https://wallaby.node.glif.io/rpc/v0](https://wallaby.node.glif.io/rpc/v0) returns chain_id 18 rather than 31415. 18 is also visible as chain_id when injected metamask set on wallaby is connected in remix.

**Comment by raulk** [comment] 2022-12-17 17:48
Duplicate of #1182.

**Closed by raulk** 2022-12-17 17:48 UTC
