### ISSUE TITLE
Logs: Duplication + nondeterminism

### ISSUE THREAD

**Issue by jaeaster** [filecoin-project/ref-fvm#1350] opened 2022-12-21 03:18 UTC
When I query for logs, I get duplicated results. I define a duplicate as multiple entries for the same `(transactionHash, logIndex)`.

I don't count logs with `removed = true` as part of the duplicate set ... but I wonder if this is expected behavior? And what does `removed = true` signify? In other EVM contexts, this would refer to logs/transactions included in Uncle'd blocks.

Possibly related, the results I receive are non-deterministic. In the example below, I can query 5 - 10 times and sometimes I receive 3 logs, other times I receive 1 log. I assume my request is routed to different nodes behind the RPC, but why do the nodes have differing state related to logs?

Code example to reproduce:
```javascript
const rpc = 'https://wallaby.node.glif.io/rpc/v1'; 
const provider = new _ethers.providers.JsonRpcProvider(rpc);

const eventInterface = new _ethers.utils.Interface([
  "event NewSale(address indexed buyer, address indexed seller, uint256 requestId, uint256 cipherId)"
]);

const address = '0xc84983B3D1338DfB08c9c539bEc01ebcaeD7e5D6';
const fromBlock = 1452;
const toBlock = 1452;
const topics = [
  eventInterface.getEventTopic("NewSale")
];

(await provider.getLogs({
  address,
  fromBlock,
  toBlock,
  topics,
})).map((log) => ({ blockHash: log.blockHash, txHash: log.transactionHash, logIndex: log.logIndex, removed: log.removed }))

=>
(3) [{…}, {…}, {…}]
[{
  blockHash: "0xd8b503c0259162514bbbb81246efe493e6379c56860abb828f7e47e11f3ca657",
  logIndex: 2,
  removed: false,
  txHash: "0x4eeb245919877e4ab8bd2f68c70243395478a74d0aac7d9c2ef7a3413b898a8b",
}, {
  blockHash: "0xd8b503c0259162514bbbb81246efe493e6379c56860abb828f7e47e11f3ca657",
  logIndex: 2,
  removed: true,
  txHash: "0x4eeb245919877e4ab8bd2f68c70243395478a74d0aac7d9c2ef7a3413b898a8b",
}, {
  blockHash: "0xd8b503c0259162514bbbb81246efe493e6379c56860abb828f7e47e11f3ca657",
  logIndex: 2,
  removed: false,
  txHash: "0x4eeb245919877e4ab8bd2f68c70243395478a74d0aac7d9c2ef7a3413b898a8b",
}]
```

**Comment by maciejwitowski** [comment] 2023-01-27 16:48
@iand wasn't able to reproduce it and suggested it may be because of glif nodes getting out of sync. (note: it was reported in Dec 2022 and a lot changed since then, also in the Logs logic so it may be invalid). Reached out to the Glif team.

**Comment by maciejwitowski** [comment] 2023-01-27 17:01
Confirmed with Glif that it should be fixed now 🥳

**Comment by tchataigner** [comment] 2023-03-16 15:47
Hey everyone ! Came after some discussions on the Slack about events being duplicated when using RPC to fetch them on Hyperspace. I currently did not tried it over Calibration or Mainnet.

I am using Ethers 5.7.2 to fetch events produced by my contracts and am getting duplicates for all events that were produced on chain. Curious about that I also tried to directly make the RPC call myself and got the same result.

I have [deployed an eth actor on Hyperspace](https://hyperspace.filfox.info/en/message/0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32) where 4 events are emitted, all of the same kind `RoleGranted`. The RPC call I'm running is this one:
```js
{
    // RPC method
    "method": "eth_getLogs",
    "params": [
        {
            // From block number of the deployment
            "fromBlock": "0x29a87",
            // Looking until lastest block 
            "toBlock": "latest",
            // Actor eth address
            "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
            "topics": [
                // RoleGranted identifier
                "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d"
            ]
        }
    ],
    "id": 44,
    "jsonrpc": "2.0"
}
``` 

Now for both those RPC URLs: `https://rpc.ankr.com/filecoin_testnet` & `https://api.hyperspace.node.glif.io/rpc/v1`

I get this response:
```json
{
  "jsonrpc": "2.0",
  "result": [
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x0000000000000000000000000000000000000000000000000000000000000000",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": false,
      "logIndex": "0x0",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    },
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x9f2df0fed2c77648de5860a4cc508cd0818c85b8b8a1ab4ceeef8d981c8956a6",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": false,
      "logIndex": "0x1",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    },
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x44ac9762eec3a11893fefb11d028bb3102560094137c3ed4518712475b2577cc",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": false,
      "logIndex": "0x2",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    },
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x59a1c48e5837ad7a7f3dcedcbe129bf3249ec4fbf651fd4f5e2600ead39fe2f5",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": false,
      "logIndex": "0x3",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    },
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x0000000000000000000000000000000000000000000000000000000000000000",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": true,
      "logIndex": "0x0",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    },
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x9f2df0fed2c77648de5860a4cc508cd0818c85b8b8a1ab4ceeef8d981c8956a6",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": true,
      "logIndex": "0x1",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    },
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x44ac9762eec3a11893fefb11d028bb3102560094137c3ed4518712475b2577cc",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": true,
      "logIndex": "0x2",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    },
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x59a1c48e5837ad7a7f3dcedcbe129bf3249ec4fbf651fd4f5e2600ead39fe2f5",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": true,
      "logIndex": "0x3",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    },
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x0000000000000000000000000000000000000000000000000000000000000000",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": false,
      "logIndex": "0x0",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    },
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x9f2df0fed2c77648de5860a4cc508cd0818c85b8b8a1ab4ceeef8d981c8956a6",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": false,
      "logIndex": "0x1",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    },
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x44ac9762eec3a11893fefb11d028bb3102560094137c3ed4518712475b2577cc",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": false,
      "logIndex": "0x2",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    },
    {
      "address": "0x778a02e2aedb80a1984bb8e88e593c1aa8de18de",
      "data": "0x",
      "topics": [
        "0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d",
        "0x59a1c48e5837ad7a7f3dcedcbe129bf3249ec4fbf651fd4f5e2600ead39fe2f5",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea",
        "0x0000000000000000000000004a441b5e77136c907d25f75262eb725d2eb48bea"
      ],
      "removed": false,
      "logIndex": "0x3",
      "transactionIndex": "0x0",
      "transactionHash": "0xdc99d8e885d6eee2575e41f19fc9b357878d38b941f35ee41b13cc5a39c65e32",
      "blockHash": "0x64f8c8101ff7c72a9ac97a838dbfc8cdfbfc6c475a803f9b84a4540bcb1d24c1",
      "blockNumber": "0x29a87"
    }
  ],
  "id": 44
}
```

We can see that we receive 3 lists of 4 elements that are concatenated.

What is interested is that:
- List 1 and 3 are the same
- Elements of list 2 are the same as the other ones except for one filed `removed` that is set to true

 Looking at the [Ethereum RPC doc from infura](https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_getlogs#result-fields) it is said that:

 `removed`: true when the log was removed, due to a chain reorganization. false if it's a valid log.

That is all I have for now, I don't have much of an insight on what could cause this :smiling_face_with_tear:  sorry about that

**Comment by Stebalien** [comment] 2023-03-17 21:58
So, the cause of this is chain reorgs and how we're handling them in the event index. Basically, we're inserting new entries every time instead of updating old ones.

The logic needs to get significantly smarter here:

1. When we revert, we need to mark every event emitted by the reverted tipset as "removed". We don't actually need to execute the tipset, we just need to all relevant events. One solution would be to just set `removed` for all events at height `>= reverted_height`.
2. When we apply a tipset, we need to:
  1. Check if we already have events from that tipset. If so, we can unset `removed` for all such events.
  2. Otherwise, add the new events.

Alternatively, for step 2, we could "upsert" new events based on the tipset cid + message cid. But that requires more indices.

**Comment by maciejwitowski** [comment] 2023-03-17 22:19
Another quicker option discussed with @Stebalien is to filter out events on the API side which is what dapp builder are doing as a workaround now. Worth considering to provide a hotfix if the solution above is not doable quick enough.

**Comment by Stebalien** [comment] 2023-03-17 22:30
Migration logic in "steb doesn't know SQL"-SQL:

1. First, delete all events from tipsets not on the main-chain. Given a tipset height (`$TSHEIGHT`) and tipset (`$TS`):
    ```sql
    DELETE FROM event WHERE tipset_cid != $TS and height = $TSHEIGHT
    ```
2. Second, find the first event from the last time the tipset was applied:
    ```sql
    SELECT id FROM event WHERE tipset_key_cid = $TS ORDER BY message_index ASC, event_index ASC, id DESC LIMIT 1
    ```
3. Finally, delete all events from times when said tipset was previously applied:
    ```sql
    DELETE FROM event WHERE tipset_key_cid = $TS AND id < $ID
    ```

Basically, this will keep the events we care about (the last recorded set of events from every block on the main chain) and delete everything else.

**Comment by iand** [comment] 2023-03-20 10:06
> So, the cause of this is chain reorgs and how we're handling them in the event index. Basically, we're inserting new entries every time instead of updating old ones.
> 
> The logic needs to get significantly smarter here:
> 
> 1. When we revert, we need to mark every event emitted by the reverted tipset as "removed". We don't actually need to parse the events in the tipset, we just need to mark all relevant events as "removed". One solution would be to just set `removed` for all events at height `>= reverted_height`.

The index receives a revert for each tipset in descending height sequence when a reorg is happening, so using `>=` would multiply the work done since it would update rows that were already set to removed=true on the pevious tipset revert. I think `set removed=true where height=? and tipset_key=?` would be more precise


> 2. When we apply a tipset, we need to:
>    
>    1. Check if we already have events from that tipset. If so, we can unset the removed field `removed` for all such events.
>    2. Otherwise, add the new events.
> 
> Alternatively, for step 2, we could "upsert" new events based on the tipset cid + message cid. But that requires more indices. As written, this requires a "by-height" and a "by tipset cid" index. Although, technically, we could get away with the latter by marking events as removed by tipset instead of by height in step 1.

I think the syntax would be (from https://www.sqlite.org/lang_UPSERT.html):

`INSERT INTO event (height, tipset_key, tipset_key_cid, emitter_addr, event_index, message_cid, message_index, reverted) VALUES(?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(height,tipset_key) DO UPDATE SET reverted=excluded.reverted`

Can `message_index` change? It's the order of the message in the tipset, We would just add `message_index=excluded.message_index` as an additional clause. Same for event_index which is tied to the order of execution of the events.

However, using upsert means adding a unique index on height,tipset_key which seems reasonable. I see that there are no indexes apart from the default primary keys, so https://github.com/filecoin-project/lotus/issues/10293 was never implemented. Maybe they can both be done at same time.

**Comment by avichalp** [comment] 2023-04-05 07:32
> Another quicker option discussed with @Stebalien is to filter out events on the API side which is what dapp builder are doing as a workaround now. Worth considering to provide a hotfix if the solution above is not doable quick enough.

Hey @maciejwitowski, could you please elaborate on how we can deduplicate the events we receive from the node as a response to the `eth_getLogs` RPC call? How do we know which ones are safe to filter out?

**Comment by fridrik01** [comment] 2023-06-26 17:18
Update, I put up a [PR](https://github.com/filecoin-project/lotus/pull/10897) that addressed this by deduping in the api layer. However, the team wants instead to solve this from the db layer instead, so I will look into address it there instead.

**Closed** 2023-06-30 11:56 UTC
Labels: Topic: Logs and events, Topic: Ethereum JSON-RPC
