### ISSUE TITLE
META: EVM Addressing & CREATE/CREATE2

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#743] opened 2022-04-01 02:31 UTC
The largest (semi)-open question for executing EVM contracts on the FVM is addressing actors on one system from the other.

The current proposed solution lives in https://github.com/filecoin-project/fvm-specs/blob/main/04-evm-mapping.md#proposed-solution-universal-stable-addresses, but has a downside: the data that goes into an address will provide the same properties as CREATE2, but won't (likely) be the exact _same_ data. For some contracts, this won't matter. For others, this could lead to subtle issues.

There are a couple of simple (if a bit ugly) solutions:

1. Make the EVM actor "special" and allow it to create new actors using the same address creation algorithm as CREATE and CREATE2.
2. Allow actors to create new addresses with an address format "language", specifying both the hashing function, and what goes into it (as long as "what goes into it" includes the sender's address). This is by far the most _flexible_ option, but also the most difficult to analyze from a security perspective.
3. Put all EVM contracts inside a single FVM-level actor with an EVM addressing scheme, using an addressing method from hierarchal consensus for communication between the EVM and other actors.

**Comment by maciejwitowski** [comment] 2022-10-07 12:57
Duplicate of https://github.com/filecoin-project/ref-fvm/issues/680

**Closed by maciejwitowski** 2022-10-07 12:58 UTC
Labels: MIGRATED
